### ISSUE TITLE
Issue with Google translate

### ISSUE THREAD

**Issue by Bamboozul** [blyad2137/google-dark-theme#31]
![Screenshot 2022-11-07 193424](https://user-images.githubusercontent.com/101983929/200377266-776bd7d4-88bf-40fd-876e-5016ba235be3.png)

[Link](https://translate.google.as/?hl=ar)

**Comment by blyad2137** [comment]
Everything done.

**Comment by Bamboozul** [comment]
![Screenshot 2022-11-08 012543](https://user-images.githubusercontent.com/101983929/200436909-3a39fa3d-7fef-4a7d-8097-8fccb2bde8ad.png)

Still have it

**Comment by blyad2137** [comment]
fixed again, but i dont know when new update will be released. lets hope it will be soon

**Comment by Bamboozul** [comment]
The text does not appear completely as it should.

![Screenshot 2023-06-19 133642](https://github.com/blyad2137/google-dark-theme/assets/101983929/6edbaf31-d105-4664-9b77-cdb7497e4dae)

![Screenshot 2023-06-19 133801](https://github.com/blyad2137/google-dark-theme/assets/101983929/9c7b0b88-79d8-49a8-988b-2f3eae315dea)

And could you please remove this?

![Screenshot 2023-06-19 133911](https://github.com/blyad2137/google-dark-theme/assets/101983929/5be7629c-3ced-48c3-bd25-8171d698081f)

![Screenshot 2023-06-19 133939](https://github.com/blyad2137/google-dark-theme/assets/101983929/8c6124dd-c26d-4885-8607-eeea54e5a229)

**Comment by blyad2137** [comment]
Done. Fix will be pushed in the next update.
Also fixed entire Translate due to Google's changes.

**Comment by Bamboozul** [comment]
> Done. Fix will be pushed in the next update. Also fixed entire Translate due to Google's changes.

Still bugged when using [arabic interface](https://translate.google.as/?hl=ar)

![Screenshot 2023-07-05 214434](https://github.com/blyad2137/google-dark-theme/assets/101983929/c2424bb6-08e7-4736-a870-f9c09b54b21c)

**Comment by Bamboozul** [comment]
> Done. Fix will be pushed in the next update. Also fixed entire Translate due to Google's changes.

The issue still persists when using the [arabic interface](https://translate.google.as/?hl=ar).

![Screenshot 2023-07-05 214434](https://github.com/blyad2137/google-dark-theme/assets/101983929/28ace05b-9ad2-4e85-8052-823e879ea3cf)

**Comment by blyad2137** [comment]
there was different code for this on arabic version since everything is on the right side. fix wil be pushed in next update
